### ISSUE TITLE
error with attrib.exe

### ISSUE THREAD

**Issue by czapa86** [xhul-dev/Saroo_-_Sort_ISO#1]
Hello,

doesn't work for me on W10 x64
I checked on two different systems and both give me:
ERROR
missing file:
"C:\WINDOWS\System32\attrib.exe"

The file is there as i checked. Running the script as admin doesn't change anything.

**Comment by xhul-dev** [comment]
Thanks a lot for the report.
That's gonna be interesting to debug, because if you're 100% sure "attrib.exe" is indeed in "C\WINDOWS\System32\\", that error shouldn't pop at all.
That means that somehow, "if not exist "%SystemRoot%\System32\attrib.exe"" returns true instead of false.
I'll write a mini debug tool tomorrow to figure out why.
Stay tuned.

**Comment by czapa86** [comment]
![obraz](https://github.com/xhul-dev/Saroo_-_Sort_ISO/assets/153087383/cb472cde-21c3-46ed-bfd7-d4627970e82c)

**Comment by xhul-dev** [comment]
> ![obraz](https://private-user-images.githubusercontent.com/153087383/327755231-cb472cde-21c3-46ed-bfd7-d4627970e82c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MTQ0NzYsIm5iZiI6MTcxNDgxNDE3NiwicGF0aCI6Ii8xNTMwODczODMvMzI3NzU1MjMxLWNiNDcyY2RlLTIxYzMtNDZlZC1iZmQ3LWQ0NjI3OTcwZTgyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQwOTE2MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWJiZmMwMDBlNmQ1ZWVjM2VmOTZjNzM4YTlkNzViNjI5ZjJmMGY5YWZiMTM0NmQ4NjQ0YTgwN2Q1ZTMzNWVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oJ2DPxRdhHb5TdggFkg7tLZ94F3p1-vu_CZptQYWh7M)

Thanks for the screenshot.
At least the date shows that it's the correct version.

As promised, i wrote a debug script (attached) that tests different ways to access "attrib.exe".
Before you ask, it doesn't write anything, so it's 100% safe.
You can execute it from anywhere.
Please let me know if it shows some numbers, and which ones.
Thanks in advance for your contribution.
[Debug_1.zip](https://github.com/xhul-dev/Saroo_-_Sort_ISO/files/15209174/Debug_1.zip)

**Comment by czapa86** [comment]
![obraz](https://github.com/xhul-dev/Saroo_-_Sort_ISO/assets/153087383/a0949f8c-a0e2-4bbe-8b93-b1ca4e81fbbd)

**Comment by xhul-dev** [comment]
> ![obraz](https://private-user-images.githubusercontent.com/153087383/327961474-a0949f8c-a0e2-4bbe-8b93-b1ca4e81fbbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NDExNTYsIm5iZiI6MTcxNDg0MDg1NiwicGF0aCI6Ii8xNTMwODczODMvMzI3OTYxNDc0LWEwOTQ5ZjhjLWEwZTItNGJiZS04YjkzLWIxY2E0ZTgxZmJiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxNjQwNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjMzN2YyMWQzMDIwNWMzNjQxNDExNWNiNjY4Njc4ZjMwNWU3NTI1ZDVmNTQzZmFkMTk0NTFlZjI2MjUxZDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E6rPvZaf3rMTWt-UeEHj07ltuiacdXdafnNzSEvXywk)

Thank you very much, i can definitely see clearer now.
The issue appears to be specific to drives mapped to servers, or when using link shell extension, which appears to be your case.
Anyway, i found a clean way to make the script work on such systems =]
I might use you one more time to test version 5 if that's OK.

**Comment by czapa86** [comment]
Sure, thanks. I find your script to be very useful so i'm here to help :)
What link shell extrnsion am i using ? .net framework ? This is the only one i know

**Comment by xhul-dev** [comment]
> Sure, thanks. I find your script to be very useful so i'm here to help :) What link shell extrnsion am i using ? .net framework ? This is the only one i know

Something like that:
https://schinagl.priv.at/nt/hardlinkshellext/hardlinkshellext.html

That, or you simply have your system connected to a private|public server or something.

From my research, it's apparently in one of those cases that the problematic syntax fails.

**Comment by czapa86** [comment]
Hmm maybe it is because i have enabled network sharing? I'm rather using standard/clean windows installation :)

**Comment by xhul-dev** [comment]
> Hmm maybe it is because i have enabled network sharing? I'm rather using standard/clean windows installation :)

That could be it, i'm not 100% sure.

Here is a version 5 test, if you have time to check it.
In theory, the issue you described should be no more.
[Saroo_-_Sort_ISO.zip](https://github.com/xhul-dev/Saroo_-_Sort_ISO/files/15213824/Saroo_-_Sort_ISO.zip)

**Comment by czapa86** [comment]
Confirmed, working now! Big Thanks!

**Comment by xhul-dev** [comment]
> Confirmed, working now! Big Thanks!

Cool.
I'll officially add version 5 to the releases tomorow.
Also, i'll add a "credits" section in the readme, and you'll definitely be listed.
Thanks again =]
